# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult.xci
set_property is_locked true [get_files E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1 -new_name Mult -ip [get_ips Mult]]

if { $cached_ip eq {} } {

synth_design -top Mult -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix Mult_ Mult.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ Mult_stub.v
 lappend ipCachedFiles Mult_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ Mult_stub.vhdl
 lappend ipCachedFiles Mult_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ Mult_sim_netlist.v
 lappend ipCachedFiles Mult_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ Mult_sim_netlist.vhdl
 lappend ipCachedFiles Mult_sim_netlist.vhdl

 config_ip_cache -add -dcp Mult.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips Mult]
}

rename_ref -prefix_all Mult_

write_checkpoint -force -noxdef Mult.dcp

catch { report_utilization -file Mult_utilization_synth.rpt -pb Mult_utilization_synth.pb }

if { [catch {
  file copy -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult.dcp E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult.dcp E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult_stub.v E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult_stub.vhdl E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult_sim_netlist.v E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.runs/Mult_synth_1/Mult_sim_netlist.vhdl E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.ip_user_files/ip/Mult]} {
  catch { 
    file copy -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.v E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.ip_user_files/ip/Mult
  }
}

if {[file isdir E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.ip_user_files/ip/Mult]} {
  catch { 
    file copy -force E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult_stub.vhdl E:/Workspace/Vivado_16.4/2017_10_30_PWM/PWM.ip_user_files/ip/Mult
  }
}
