# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PWM.xdc

# IP: E:/Workspace/Vivado_16.4/2017_10_30_PWM/Design/IP_Core/MULT/Mult/Mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mult || ORIG_REF_NAME==Mult}]
