# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2017_10_28_PWM/PWM.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2017_10_28_PWM/PWM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2017_10_28_PWM/PWM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/Workspace/Vivado_16.4/2017_10_28_PWM/Design/Code/PWM.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Workspace/Vivado_16.4/2017_10_28_PWM/PWM.srcs/PWM_2/new/PWM.xdc
set_property used_in_implementation false [get_files E:/Workspace/Vivado_16.4/2017_10_28_PWM/PWM.srcs/PWM_2/new/PWM.xdc]


synth_design -top PWM -part xc7a35tcpg236-1


write_checkpoint -force -noxdef PWM.dcp

catch { report_utilization -file PWM_utilization_synth.rpt -pb PWM_utilization_synth.pb }
