set_property PACKAGE_PIN V16 [get_ports key1]
set_property PACKAGE_PIN W16 [get_ports key2]
set_property PACKAGE_PIN W5 [get_ports sclk]
set_property PACKAGE_PIN J1 [get_ports PWM]
set_property IOSTANDARD LVTTL [get_ports PWM]
set_property IOSTANDARD LVTTL [get_ports key1]
set_property IOSTANDARD LVTTL [get_ports key2]
set_property IOSTANDARD LVTTL [get_ports sclk]


set_property PACKAGE_PIN V17 [get_ports key0]
set_property PACKAGE_PIN W17 [get_ports key3]
set_property PACKAGE_PIN W15 [get_ports key4]
set_property PACKAGE_PIN V15 [get_ports key5]
set_property PACKAGE_PIN W14 [get_ports key6]
set_property IOSTANDARD LVTTL [get_ports key4]
set_property IOSTANDARD LVTTL [get_ports key5]
set_property IOSTANDARD LVTTL [get_ports key3]
set_property IOSTANDARD LVTTL [get_ports key0]
set_property IOSTANDARD LVTTL [get_ports key6]
